HSHELL_WINDOWCREATED = 1
# noinspection SpellCheckingInspection
HSHELL_WINDOWDESTROYED = 2
# noinspection SpellCheckingInspection
HSHELL_ACTIVATESHELLWINDOW = 3
# noinspection SpellCheckingInspection
HSHELL_WINDOWACTIVATED = 32772
# noinspection SpellCheckingInspection
HSHELL_GETMINRECT = 5
# noinspection SpellCheckingInspection
HSHELL_REDRAW = 6
# noinspection SpellCheckingInspection
HSHELL_TASKMAN = 7
# noinspection SpellCheckingInspection
HSHELL_LANGUAGE = 8
# noinspection SpellCheckingInspection
HSHELL_ACCESSIBILITYSTATE = 11
# noinspection SpellCheckingInspection
HSHELL_APPCOMMAND = 12
# noinspection SpellCheckingInspection
HSHELL_HIGHBIT = 0x8000
# noinspection SpellCheckingInspection
HSHELL_FLASH = (HSHELL_REDRAW | HSHELL_HIGHBIT)
# noinspection SpellCheckingInspection
HSHELL_WINDOWFULLSCREEN = 53
# noinspection SpellCheckingInspection
HSHELL_WINDOWNORMAL = 54
